/**
 * Generates a 256-bit AES key using the Web Crypto API
 * @returns A promise that resolves with a 256-bit AES CryptoKey
 * @throws If key generation fails
 */
export async function generateAES256Key(): Promise<CryptoKey> {
  try {
    const key = await crypto.subtle.generateKey(
      {
        name: 'AES-GCM',
        length: 256,
      },
      true, // extractable
      ['encrypt', 'decrypt'] // keyUsages
    );

    return key;
  } catch (error) {
    throw new Error(`Error generating AES 256 key: ${error}`);
  }
}

/**
 * Encryption result containing the encrypted data and IV
 */
export interface EncryptedData {
  /** The encrypted data */
  ciphertext: ArrayBuffer;
  /** The initialization vector used for encryption */
  iv: Uint8Array<ArrayBuffer>;
}

/**
 * Encrypts a buffer using a 256-bit AES-GCM key
 * @param key - The CryptoKey generated by generateAES256Key
 * @param data - The buffer to encrypt (BufferSource)
 * @returns A promise that resolves with the encrypted data and IV
 * @throws If encryption fails
 */
export async function encryptBuffer(
  key: CryptoKey,
  data: BufferSource
): Promise<EncryptedData> {
  try {
    // Generate a random 12-byte IV (recommended for AES-GCM)
    const iv = crypto.getRandomValues(new Uint8Array(12));

    // Encrypt the data
    const ciphertext = await crypto.subtle.encrypt(
      {
        name: 'AES-GCM',
        iv,
      },
      key,
      data
    );

    return {
      ciphertext,
      iv,
    };
  } catch (error) {
    throw new Error(`Error encrypting buffer: ${error}`);
  }
}

/**
 * Decrypts an encrypted buffer using a 256-bit AES-GCM key
 * @param key - The CryptoKey generated by generateAES256Key
 * @param encryptedData - The encrypted data containing ciphertext and IV
 * @returns A promise that resolves with the decrypted data as ArrayBuffer
 * @throws If decryption fails
 */
export async function decryptBuffer(
  key: CryptoKey,
  encryptedData: EncryptedData
): Promise<ArrayBuffer> {
  try {
    // Decrypt the data using the same IV that was used for encryption
    const decryptedData = await crypto.subtle.decrypt(
      {
        name: 'AES-GCM',
        iv: encryptedData.iv,
      },
      key,
      encryptedData.ciphertext
    );

    return decryptedData;
  } catch (error) {
    throw new Error(`Error decrypting buffer: ${error}`);
  }
}

/**
 * Converts a text string to an ArrayBuffer
 * @param text - The text string to convert
 * @returns The text as an ArrayBuffer
 */
export function textToBuffer(text: string): ArrayBuffer {
  const encoder = new TextEncoder();
  return encoder.encode(text).buffer;
}

/**
 * Converts an ArrayBuffer to a text string
 * @param buffer - The ArrayBuffer to convert
 * @returns The buffer as a text string
 */
export function bufferToText(buffer: ArrayBuffer): string {
  const decoder = new TextDecoder();
  return decoder.decode(buffer);
}

/**
 * Exports a CryptoKey to a base64 string for storage
 * @param key - The CryptoKey to export
 * @returns A promise that resolves with the key as a base64 string
 * @throws If key export fails
 */
export async function exportKeyToBase64(key: CryptoKey): Promise<string> {
  const keyBytes = await exportKeyToUint8Array(key);
  return uint8ArrayToBase64(keyBytes);
}

/**
 * Exports a CryptoKey to a Uint8Array
 * @param key - The CryptoKey to export
 * @returns A promise that resolves with the key as a Uint8Array
 * @throws If key export fails
 */
export async function exportKeyToUint8Array(key: CryptoKey): Promise<Uint8Array> {
  try {
    const exported = await crypto.subtle.exportKey('raw', key);
    return new Uint8Array(exported);
  } catch (error) {
    throw new Error(`Error exporting key to Uint8Array: ${error}`);
  }
}

/**
 * Imports a Uint8Array as a CryptoKey
 * @param keyBytes - The Uint8Array representing the key
 * @returns A promise that resolves with the imported CryptoKey
 * @throws If key import fails
 */
export async function importKeyFromUint8Array(keyBytes: Uint8Array<ArrayBuffer>): Promise<CryptoKey> {
  try {
    return await crypto.subtle.importKey(
      'raw',
      keyBytes,
      {
        name: 'AES-GCM',
        length: 256,
      },
      true, // extractable
      ['encrypt', 'decrypt'] // keyUsages
    );
  } catch (error) {
    throw new Error(`Error importing key from Uint8Array: ${error}`);
  }
}

/**
 * Converts a Uint8Array to a base64 string
 * @param bytes - The Uint8Array to convert
 * @returns The base64 string
 */
export function uint8ArrayToBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

/**
 * Converts a base64 string to a Uint8Array
 * @param base64 - The base64 string to convert
 * @returns The Uint8Array
 */
export function base64ToUint8Array(base64: string): Uint8Array<ArrayBuffer> {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

/**
 * Converts an ArrayBuffer to a base64 string
 * @param buffer - The ArrayBuffer to convert
 * @returns The base64 string
 */
export function arrayBufferToBase64(buffer: ArrayBuffer): string {
  return uint8ArrayToBase64(new Uint8Array(buffer));
}

/**
 * Imports a base64 string as a CryptoKey
 * @param base64Key - The base64 string representing the key
 * @returns A promise that resolves with the imported CryptoKey
 * @throws If key import fails
 */
export async function importKeyFromBase64(base64Key: string): Promise<CryptoKey> {
  const keyBytes = base64ToUint8Array(base64Key);
  return importKeyFromUint8Array(keyBytes);
}


async function getKeyFromPasswordAndSalt(password: string, salt: Uint8Array<ArrayBuffer>) {
  const enc = new TextEncoder();
  const keyMaterial = await window.crypto.subtle.importKey(
    "raw",
    enc.encode(password),
    "PBKDF2",
    false,
    ["deriveBits", "deriveKey"],
  );
  const key = await window.crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      salt: salt,
      iterations: 100000,
      hash: "SHA-256",
    },
    keyMaterial,
    { name: "AES-GCM", length: 256 },
    true,
    ["encrypt", "decrypt"],
  );
  return key
}


export interface EncryptedDataWithPassword {
  salt: Uint8Array<ArrayBuffer>;
  iv: Uint8Array<ArrayBuffer>;
  ciphertext: ArrayBuffer; 
}

export async function encryptBufferWithPassword(buffer: BufferSource, password: string): Promise<EncryptedDataWithPassword> {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const key = await getKeyFromPasswordAndSalt(password, salt);
  const encryptedData = await encryptBuffer(key, buffer);
  return {
    ...encryptedData,
    salt,
  };
}

export async function decryptBufferWithPassword(encryptedData: EncryptedDataWithPassword, password: string): Promise<ArrayBuffer> {
  const key = await getKeyFromPasswordAndSalt(password, encryptedData.salt);
  const decryptedData = await decryptBuffer(key, {
    ciphertext: encryptedData.ciphertext,
    iv: encryptedData.iv,
  });
  return decryptedData;
}