/**
 * Generates a 256-bit AES key using the Web Crypto API
 * @returns A promise that resolves with a 256-bit AES CryptoKey
 * @throws If key generation fails
 */
export async function generateAES256Key(): Promise<CryptoKey> {
  try {
    const key = await crypto.subtle.generateKey(
      {
        name: 'AES-GCM',
        length: 256,
      },
      true, // extractable
      ['encrypt', 'decrypt'] // keyUsages
    );

    return key;
  } catch (error) {
    throw new Error(`Error generating AES 256 key: ${error}`);
  }
}

/**
 * Encryption result containing the encrypted data and IV
 */
export interface EncryptedData {
  /** The encrypted data */
  ciphertext: ArrayBuffer;
  /** The initialization vector used for encryption */
  iv: Uint8Array;
}

/**
 * Encrypts a buffer using a 256-bit AES-GCM key
 * @param key - The CryptoKey generated by generateAES256Key
 * @param data - The buffer to encrypt (BufferSource)
 * @returns A promise that resolves with the encrypted data and IV
 * @throws If encryption fails
 */
export async function encryptBuffer(
  key: CryptoKey,
  data: BufferSource
): Promise<EncryptedData> {
  try {
    // Generate a random 12-byte IV (recommended for AES-GCM)
    const iv = crypto.getRandomValues(new Uint8Array(12));

    // Encrypt the data
    const ciphertext = await crypto.subtle.encrypt(
      {
        name: 'AES-GCM',
        iv: iv,
      },
      key,
      data
    );

    return {
      ciphertext,
      iv,
    };
  } catch (error) {
    throw new Error(`Error encrypting buffer: ${error}`);
  }
}

/**
 * Decrypts an encrypted buffer using a 256-bit AES-GCM key
 * @param key - The CryptoKey generated by generateAES256Key
 * @param encryptedData - The encrypted data containing ciphertext and IV
 * @returns A promise that resolves with the decrypted data as ArrayBuffer
 * @throws If decryption fails
 */
export async function decryptBuffer(
  key: CryptoKey,
  encryptedData: EncryptedData
): Promise<ArrayBuffer> {
  try {
    // Decrypt the data using the same IV that was used for encryption
    const decryptedData = await crypto.subtle.decrypt(
      {
        name: 'AES-GCM',
        iv: new Uint8Array(encryptedData.iv),
      },
      key,
      encryptedData.ciphertext
    );

    return decryptedData;
  } catch (error) {
    throw new Error(`Error decrypting buffer: ${error}`);
  }
}

/**
 * Converts a text string to an ArrayBuffer
 * @param text - The text string to convert
 * @returns The text as an ArrayBuffer
 */
export function textToBuffer(text: string): ArrayBuffer {
  const encoder = new TextEncoder();
  return encoder.encode(text).buffer;
}

/**
 * Converts an ArrayBuffer to a text string
 * @param buffer - The ArrayBuffer to convert
 * @returns The buffer as a text string
 */
export function bufferToText(buffer: ArrayBuffer): string {
  const decoder = new TextDecoder();
  return decoder.decode(buffer);
}

/**
 * Exports a CryptoKey to a base64 string for storage
 * @param key - The CryptoKey to export
 * @returns A promise that resolves with the key as a base64 string
 * @throws If key export fails
 */
export async function exportKeyToBase64(key: CryptoKey): Promise<string> {
  try {
    const exported = await crypto.subtle.exportKey('raw', key);
    const bytes = new Uint8Array(exported);
    // Convert to base64
    let binary = '';
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  } catch (error) {
    throw new Error(`Error exporting key to base64: ${error}`);
  }
}

/**
 * Imports a base64 string as a CryptoKey
 * @param base64Key - The base64 string representing the key
 * @returns A promise that resolves with the imported CryptoKey
 * @throws If key import fails
 */
export async function importKeyFromBase64(base64Key: string): Promise<CryptoKey> {
  try {
    // Convert base64 to ArrayBuffer
    const binary = atob(base64Key);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    
    return await crypto.subtle.importKey(
      'raw',
      bytes.buffer,
      {
        name: 'AES-GCM',
        length: 256,
      },
      true, // extractable
      ['encrypt', 'decrypt'] // keyUsages
    );
  } catch (error) {
    throw new Error(`Error importing key from base64: ${error}`);
  }
}
